---

  - name: Install Nginx
    apt: pkg=nginx state=installed update_cache=true
    notify:
      - Start Nginx
      - Create nginx config backup directory
      - Backup and Remove nginx default config