---

- name: Install Postgres and libraries
  apt: pkg={{ item }} state=latest
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2

- name: Create db user
  sudo_user: postgres
  command: psql -c "CREATE USER {{ database_user }} WITH PASSWORD '{{ db_password }}';"
  ignore_errors: yes